# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.5.0
#     networks:
#       - app-net
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000

#   kafka:
#     image: wurstmeister/kafka:2.13-2.8.1
#     networks:
#       - app-net
#     depends_on:
#       - zookeeper
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

#   producer:
#     build: ./producer
#     networks:
#       - app-net
#     depends_on:
#       - kafka
#     environment:
#       BOOTSTRAP_SERVERS: kafka:9092
#     restart: on-failure

#   cassandra:
#     image: cassandra:4.1
#     networks:
#       - app-net
#     ports:
#       - "9042:9042"

#   spark:
#     image: bitnami/spark:latest
#     networks:
#       - app-net
#     ports:
#       - "4040:4040"
#     depends_on:
#       - kafka
#       - cassandra
#     volumes:
#       - ./spark_scripts:/opt/spark_apps

# networks:
#   app-net:









services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    networks:
      - app-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    networks:
      - app-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    image: cassandra:4.1
    networks:
      - app-net
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra:/cassandra-init

  producer:
    build: ./producer
    networks:
      - app-net
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  spark:
    image: bitnami/spark:latest
    networks:
      - app-net
    depends_on:
      - kafka
      - cassandra
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
      - SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/custom-jars/*
    volumes:
      - ./spark_scripts:/opt/spark_apps
      - ./spark_scripts/jars:/opt/bitnami/spark/custom-jars
      - ./spark_scripts:/opt/bitnami/spark/scripts


      

networks:
  app-net:
