
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
    depends_on:
      - kafka
      - cassandra
    volumes:
      - ./spark_scripts:/opt/spark_apps
